### ISSUE TITLE
generate a set of concept set datafile to manage the bulk import of concept sets to the enclave.

### ISSUE THREAD

**Issue by stephanieshong** [HOT-Ecosystem/ValueSet-Tools#12]
Concept set can be created _(edit: Joe: In the future when they have added this feature)_ via a bulk import process and by pass the concept set editor for importing a bulk of externally authorized concept sets.  Specify detail specification to handle this process. 

Tables needed to generate _(edit: Joe: Added links)_: 
- [x] 1. concept set container: (`concept_set_container_edited` table)
- [x] 2. concept set version: (`code_sets` table)
- [x] 3. concept set metadata: (`concept_set_version_item_rv_edited` table)

More details will be uploaded. This is a place holder issues for Joe and Steph.

**Comment by joeflack4** [comment]
Needs clarification: Not yet ready to work on, as the "bulk upload" feature has not yet been implemented in the Enclave. Stephanie and Joe will meet to discuss this after Joe returns from vacation on the 18th.

**Comment by joeflack4** [comment]
Currently, the process is quite arduous:

<img width="499" alt="1" src="https://user-images.githubusercontent.com/13045020/149169023-6de327c8-c7c9-4f64-80c0-9f72622c721b.png">


<img width="1313" alt="2- check all concepts" src="https://user-images.githubusercontent.com/13045020/149169026-a64c8626-efdf-4077-8fde-335af75a4ef2.png">


<img width="1305" alt="3 - check all concept descendants" src="https://user-images.githubusercontent.com/13045020/149169027-b0c78c74-3653-4c98-be89-a95c7d576dab.png">

**Comment by joeflack4** [comment]
TODOs as discussed at today's meeting w/ Joe & Stephanie (exported from Workflowy):

```
create new csv

- cli options to add
  - atlas + JSON (siggie working on this)
    - 2 options
  - palantir-concept-set
    - that's what to call this data model. its not same as omop
- later:
  - don't need
    - concept_relationship
  - 2 other tables stephanie said we may need to do later:
    - concept_set_container_edited
      - https://unite.nih.gov/workspace/data-integration/dataset/preview/ri.foundry.main.dataset.8cb458de-6937-4f50-8ef5-2b345382dbd4/master
      - PK: concept_set_id
    - code_sets
      - PK / FK: concept_set_name
        - links to: concept_set_container_edited
- concept_set_version_item_rv_edited *just this one for now*
  - main columns
    - codeset_id: leave blank
      - they need to uniquely create
    - concept_id: leave blank *
      - stephanie can do
    - isExcluded: always false
    - includeDescendants: always true
    - includeMapped: always false
    - item_id: leave blank
      - or can leave off, and they can autogen
      - or i can autogen my own uuid
      - but i think just leave this column out
    - annotation
      - literal string: "Generated from VSAC export"
    - created_by: "DI&H Bulk Import"
      - they can autogen this based on who is logged in
      - or i could leave blank
      - could do this literal string (do this for now)
    - created_at: leave blank
      - though I could populate myself
  - same as this table, except add one column:
  - 2 new columns:
    - code
      - put the codes here
    - codeSystem
      - i.e. ICD10CM, or SNOMEDCT
      - exactly as spelled from VSAC

```
